### ISSUE TITLE
Login successful, but cannot refresh token, fetch updates and discover devices

### ISSUE THREAD

**Issue by hgchen** [grivkees/homebridge-carrier-infinity#96] opened 2021-08-31 19:19 UTC
**Describe The Bug:**
Login successful, but cannot refresh token (error code 400), fetch updates (error code 401) and discover devices

**To Reproduce:**
- Bryant Evolution Connex
- Homebridage v 1.3.4

**Expected behavior:**
Should be able to refresh token, fetch updates and discover devices.

**Logs:**
[8/31/2021, 12:17:14 PM] Homebridge v1.3.4 (homebridge-carrier-infinity) is running on port 53772.
[8/31/2021, 12:17:14 PM] [homebridge-carrier-infinity] Could not refresh api access token:  Request failed with status code 400
[8/31/2021, 12:17:14 PM] [homebridge-carrier-infinity] Login success!
[8/31/2021, 12:17:14 PM] [homebridge-carrier-infinity] Failed to fetch updates:  Request failed with status code 401
[8/31/2021, 12:17:14 PM] [homebridge-carrier-infinity] Could not discover devices: Cannot read property 'locations' of null

**Plugin Config:**

{
    "username": "reducted",
    "password": "reducted",
    "holdBehavior": "for_x",
    "holdArgument": "01:00",
    "showOutdoorTemperatureSensor": true,
    "showFanControl": true,
    "showIndoorHumiditySensors": true,
    "platform": "CarrierInfinity",
    "_bridge": {
        "username": "reducted",
        "port": 53772
    }
}

**Screenshots:**
<img width="917" alt="image" src="https://user-images.githubusercontent.com/12928760/131562783-a4257d6e-e96f-4354-b435-8150547fe3de.png">

**Environment:**

* **Plugin Version**: 1.4.0
* **Homebridge Version**: 1.3.4
* **Node.js Version**: v14.17.5 
* **NPM Version**: v6.14.14 
* **Operating System**: Docker on Synology

**Comment by grivkees** [comment] 2021-09-30 01:00
hey! thanks for submitting the issue.

Turns out the 'Login success!' message was lying. Releasing a new version on @next shortly that has some improved logging. If you can give this new version a try and share the logs it generates, I'll be able to take a closer look.

**Comment by SenseBrainTech** [comment] 2021-09-30 05:14
> hey! thanks for submitting the issue.
> 
> Turns out the 'Login success!' message was lying. Releasing a new version on @next shortly that has some improved logging. If you can give this new version a try and share the logs it generates, I'll be able to take a closer look.

Hi, thanks for taking the time to look at my issue. I've updated the plugin to the latest version in Homebridge. Here's the new log I have.

`[9/29/2021, 10:10:48 PM] [homebridge-carrier-infinity] Launched child bridge with PID 2712
[9/29/2021, 10:10:48 PM] Registering platform 'homebridge-carrier-infinity.CarrierInfinity'
[9/29/2021, 10:10:48 PM] [homebridge-carrier-infinity] Loaded homebridge-carrier-infinity v1.5.4 child bridge successfully
[9/29/2021, 10:10:48 PM] Loaded 0 cached accessories from cachedAccessories.0EFBA7224D37.
Preparing Advertiser for 'homebridge-carrier-infinity 17E4' using bonjour-hap backend!
Starting to advertise 'homebridge-carrier-infinity 17E4' using bonjour-hap backend!
[9/29/2021, 10:10:48 PM] Homebridge v1.3.4 (homebridge-carrier-infinity) is running on port 53772.
[9/29/2021, 10:10:49 PM] [homebridge-carrier-infinity] Could not refresh api access token:  Request failed with status code 400 
Status:  400 
Data:  <error version="1.48"><message>username empty</message></error>
[9/29/2021, 10:10:49 PM] [homebridge-carrier-infinity] Failed to fetch updates (axios):  Request failed with status code 401
[9/29/2021, 10:10:49 PM] [homebridge-carrier-infinity] Could not discover devices: Cannot read property 'locations' of null`

**Comment by hgchen** [comment] 2021-09-30 05:16
> hey! thanks for submitting the issue.
> 
> Turns out the 'Login success!' message was lying. Releasing a new version on @next shortly that has some improved logging. If you can give this new version a try and share the logs it generates, I'll be able to take a closer look.

Hi, thanks for taking the time to look at my issue. I've updated the plugin to the latest version in Homebridge. Here's the new log I have.

`[9/29/2021, 10:10:48 PM] [homebridge-carrier-infinity] Launched child bridge with PID 2712
[9/29/2021, 10:10:48 PM] Registering platform 'homebridge-carrier-infinity.CarrierInfinity'
[9/29/2021, 10:10:48 PM] [homebridge-carrier-infinity] Loaded homebridge-carrier-infinity v1.5.4 child bridge successfully
[9/29/2021, 10:10:48 PM] Loaded 0 cached accessories from cachedAccessories.0EFBA7224D37.
Preparing Advertiser for 'homebridge-carrier-infinity 17E4' using bonjour-hap backend!
Starting to advertise 'homebridge-carrier-infinity 17E4' using bonjour-hap backend!
[9/29/2021, 10:10:48 PM] Homebridge v1.3.4 (homebridge-carrier-infinity) is running on port 53772.
[9/29/2021, 10:10:49 PM] [homebridge-carrier-infinity] Could not refresh api access token:  Request failed with status code 400 
Status:  400 
Data:  <error version="1.48"><message>username empty</message></error>
[9/29/2021, 10:10:49 PM] [homebridge-carrier-infinity] Failed to fetch updates (axios):  Request failed with status code 401
[9/29/2021, 10:10:49 PM] [homebridge-carrier-infinity] Could not discover devices: Cannot read property 'locations' of null`

**Comment by grivkees** [comment] 2021-09-30 22:40
@hgchen The only way I'm able to reproduce is if the username is an empty string in the config. Do you see this message anywhere in the logs "[CarrierInfinity] Username and password do not appear to be set in config. This is not going to work."
Can you confirm your config does have a username set? Are there any special characters or numbers in your username? Can you try removing the "_bridge" section and see if that helps?

**Comment by grivkees** [comment] 2021-11-10 00:40
Not able to reproduce this. And as far as I can tell this was a login issue due to a missing username. Newer versions of the plug-in have better logging to help debug these issues. Which should hopefully make this clearer. 

Going to close the issue for now. But please don’t hesitate to reopen if you’re still having the issue.

**Comment by hgchen** [comment] 2021-11-10 20:52
> @hgchen The only way I'm able to reproduce is if the username is an empty string in the config. Do you see this message anywhere in the logs "[CarrierInfinity] Username and password do not appear to be set in config. This is not going to work." Can you confirm your config does have a username set? Are there any special characters or numbers in your username? Can you try removing the "_bridge" section and see if that helps?

Hi there, 
Sorry for the delayed replay. I think I found the cause of the problem. My previous password contains a lot of special symbols. I changed the password to a simpler one with fewer special symbols, and it just worked. The previous complex password contains symbols including the following: "#&*^%". Not sure which one caused the problem.
Thanks again for the help.

**Comment by grivkees** [comment] 2021-11-12 01:00
Ah. Interesting.
I’ll reopen to check how special characters work in passwords. I definitely want it to work with strong passwords.
Thanks!

**Comment by KayakJim** [comment] 2021-12-04 13:38
Had the same issue with complex password "TkW&@8EWnjXVtMk)pnR=cyEg".  Changed password to use only _$ (underscore and dollar sign) along with upper/lower case and numbers and it started working.

**Closed** 2022-02-15 02:59 UTC
Labels: bug
