### ISSUE TITLE
Incorrect temperature shown

### ISSUE THREAD

**Issue by ksdennis** [grivkees/homebridge-carrier-infinity#238] opened 2022-05-13 17:51 UTC
The incorrect temperature is shown on all three thermostat devices (34 F).  Also, the following error occurs when the Homebridge is rebooted, that seems related:  "This plugin threw an error from the characteristic 'Current Temperature': Unhandled error thrown inside read handler for characteristic: This callback function has already been called by someone else; it can only be called one time.. See https://homebridge.io/w/JtMGR for more info."  The error is shown three times, once for each thermostat device.

**Comment by grivkees** [comment] 2022-06-04 04:42
Hey @ksdennis, can you fill out the bug context questions below? Thanks!

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by grivkees** [comment] 2022-06-28 02:12
Closing as unable to reproduce. If you're still having the issue, please fill out the above, and reopen the issue. Thanks!

**Closed by grivkees** 2022-06-28 02:12 UTC
Labels: bug, blocked
