### ISSUE TITLE
Promises not being evaluated [prev: Outdoor temperature & fan speed wrong and characteristic warnings for plugin]

### ISSUE THREAD

**Issue by tmills1073** [grivkees/homebridge-carrier-infinity#132] opened 2021-11-09 16:20 UTC
**Describe Your Problem:**
The outdoor temperature sensor on Model 'SYSTXCCITC01-B' is stuck at 32 degrees.  I can see the correct outdoor temperature on the unit (carrier) and on their website when I sign in.  The fan control is also showing off, when it's running. I am also getting characteristic issues for a number of settings.

**Logs:**

```
[11/9/2021, 10:53:32 AM] [CarrierInfinity] Adding new accessory:  ZONE 1 Environmental Sensor
[11/9/2021, 10:53:32 AM] [CarrierInfinity] Discovered outdoor temp sensor device serial:xxxxxxxx
[11/9/2021, 10:53:32 AM] [CarrierInfinity] Adding new accessory:  Outdoor Temperature
[11/9/2021, 10:53:44 AM] [homebridge-carrier-infinity] This plugin generated a warning from the characteristic 'Current Heating Cooling State': characteristic value expected valid finite number and received "[object Promise]" (object). See https://git.io/JtMGR for more info.
[11/9/2021, 10:53:44 AM] [homebridge-carrier-infinity] This plugin generated a warning from the characteristic 'Target Heating Cooling State': characteristic value expected valid finite number and received "[object Promise]" (object). See https://git.io/JtMGR for more info.
[11/9/2021, 10:53:44 AM] [homebridge-carrier-infinity] This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected valid finite number and received "[object Promise]" (object). See https://git.io/JtMGR for more info.
[11/9/2021, 10:53:44 AM] [homebridge-carrier-infinity] This plugin generated a warning from the characteristic 'Target Temperature': characteristic value expected valid finite number and received "[object Promise]" (object). See https://git.io/JtMGR for more info.
[11/9/2021, 10:53:44 AM] [homebridge-carrier-infinity] This plugin generated a warning from the characteristic 'Temperature Display Units': characteristic value expected valid finite number and received "[object Promise]" (object). See https://git.io/JtMGR for more info.
[11/9/2021, 10:53:44 AM] [homebridge-carrier-infinity] This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': characteristic value expected valid finite number and received "[object Promise]" (object). See https://git.io/JtMGR for more info.
[11/9/2021, 10:53:44 AM] [homebridge-carrier-infinity] This plugin generated a warning from the characteristic 'Heating Threshold Temperature': characteristic value expected valid finite number and received "[object Promise]" (object). See https://git.io/JtMGR for more info.
[11/9/2021, 10:53:44 AM] [homebridge-carrier-infinity] This plugin generated a warning from the characteristic 'Filter Life Level': characteristic value expected valid finite number and received "[object Promise]" (object). See https://git.io/JtMGR for more info.
[11/9/2021, 10:53:44 AM] [homebridge-carrier-infinity] This plugin generated a warning from the characteristic 'Filter Change Indication': characteristic value expected valid finite number and received "[object Promise]" (object). See https://git.io/JtMGR for more info.
[11/9/2021, 10:53:44 AM] [homebridge-carrier-infinity] This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic value expected valid finite number and received "[object Promise]" (object). See https://git.io/JtMGR for more info.
[11/9/2021, 10:53:44 AM] [homebridge-carrier-infinity] This plugin generated a warning from the characteristic 'Active': characteristic value expected valid finite number and received "[object Promise]" (object). See https://git.io/JtMGR for more info.
[11/9/2021, 10:53:44 AM] [homebridge-carrier-infinity] This plugin generated a warning from the characteristic 'Rotation Speed': characteristic value expected valid finite number and received "[object Promise]" (object). See https://git.io/JtMGR for more info.
[11/9/2021, 10:53:44 AM] [homebridge-carrier-infinity] This plugin generated a warning from the characteristic 'Target Fan State': characteristic value expected valid finite number and received "[object Promise]" (object). See https://git.io/JtMGR for more info.
[11/9/2021, 10:53:44 AM] [homebridge-carrier-infinity] This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic value expected valid finite number and received "[object Promise]" (object). See https://git.io/JtMGR for more info.
[11/9/2021, 10:53:44 AM] [homebridge-carrier-infinity] This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected valid finite number and received "[object Promise]" (object). See https://git.io/JtMGR for more info.
```

**Plugin Config:**

```json
 {
            "username": "username",
            "password": "password",
            "holdBehavior": "activity",
            "showOutdoorTemperatureSensor": true,
            "showFanControl": true,
            "showIndoorHumiditySensors": true,
            "platform": "CarrierInfinity"
        },
```

**Screenshots:**

![image](https://user-images.githubusercontent.com/15236550/140961992-c93ea533-a877-48e2-8128-84b433b54a5f.png)
![image](https://user-images.githubusercontent.com/15236550/140962047-2c45c050-1b1e-467d-92ea-ba6d1bcf4209.png)
![image](https://user-images.githubusercontent.com/15236550/140962677-0ca5e95c-cecf-45de-a0bb-272ee721e9c1.png)

**Environment:**

* **Plugin Version**: homebridge-carrier-infinity v1.5.4
* **Homebridge Version**:  v1.3.5
* **Node.js Version**: v16.13.0 
* **NPM Version**: v8.1.0
* **Operating System**: Docker | Ubuntu Bionic Beaver (18.04.6 LTS)

**Comment by grivkees** [comment] 2021-11-10 00:35
Hey. Thanks for reporting! This is really weird. It looks like it’s not working at all. It’s just not actually running the code correctly.

Not sure what’s going on here. Ill have to look into it deeper. I see you’re running a newer version of node than I am. I’ll try to see if i can reproduce by running on the version you are.

In the meantime, I’d recommend trying the old standby: uninstalling and reinstalling, and turning it on and off.

**Comment by tmills1073** [comment] 2021-11-12 18:28
Thanks! The old standby didn't work, but thanks for taking a look at this!

**Comment by grivkees** [comment] 2022-02-15 05:06
Hey,

I'm unfortunately not able to reproduce. By chance are you using any other homebridge plugins, and do they exhibit the same behavior? If not, could you try another plugin and see if it happens to that one too.

High level, for some reason the promise (async code) isn't being executed before it gets passed to the homekit bridge. But that execution is part of what homebridge itself is supposed to do, so I'm wondering if it is maybe an issue with homebridge itself.

If you can confirm other plugins are working, can you update to the latest node version (16.14.0) and see if that works?

**Comment by tmills1073** [comment] 2022-02-15 15:46
No luck - same issue. 32

[image: image.png]
[image: image.png]

Thanks for looking into it.  Any logs I can send?

**Comment by grivkees** [comment] 2022-03-03 04:40
Just pushed some changes to the "next" channel. It has some unrelated changes, but its possible it may help indirectly.

Give it a try when you get a chance and let me know if this seems resolved.

npm install -g homebridge-carrier-infinity@next

**Comment by grivkees** [comment] 2022-04-20 03:26
Hey @tmills1073, when you get a chance, let me know if the latest version helps out at all. 

Changes were pushed to latest, so you can try out the stable version now. Either you can click the update button in homebridge ui, or npm update the plugin.

**Comment by grivkees** [comment] 2022-06-04 04:21
Closing since I think this is fixed and can't reproduce the issue. If you are still experiencing the issue, please reopen and I'll keep investigating. Thanks!

**Closed by grivkees** 2022-06-04 04:21 UTC
Labels: bug, blocked
